# Generated by Django 6.0.2 on 2026-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READ', 'Read'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
