# Generated by Django 6.0.2 on 2026-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PAID_LATE', 'Paid Late'), ('OVERDUE', 'Overdue'), ('UNPAID', 'Pending')], default='UNPAID', max_length=10),
        ),
    ]
