# Generated by Django 6.0.2 on 2026-04-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='room',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
